### ISSUE TITLE
Get nothing when use `fluid_job_dist_train.yaml` to create PaddleJob 

### ISSUE THREAD

**Issue by a6802739** [PaddlePaddle/paddle-k8s-operator#1]
第一步，使用`kubectl create -f manifests/` 安装 PaddleJob。结果如下：
```
[root@vbj-basictech-chenchao-3 paddle-k8s-operator]# kubectl create -f manifests/
customresourcedefinition.apiextensions.k8s.io/paddlejobs.paddlepaddle.org created
deployment.extensions/paddle-operator created
clusterrole.rbac.authorization.k8s.io/paddle-operator created
clusterrolebinding.rbac.authorization.k8s.io/paddle-operator created
```
第二步，使用`kubectl create -f example/fluid/dist_train/fluid_job_dist_train.yaml` create 一个PaddleJob。结果如下：
```
[root@vbj-basictech-chenchao-3 paddle-k8s-operator]# kubectl create -f example/fluid/dist_train/fluid_job_dist_train.yaml
paddlejob.paddlepaddle.org/songhao-test-paddle-job created
```
第三部，查看pods创建情况：
```
[root@vbj-basictech-chenchao-3 paddle-k8s-operator]# kubectl get pods
NAME                                                  READY   STATUS      RESTARTS   AGE
cephfs-m-tf-inference-deployment-5d4f946c89-crsdw     1/1     Running     1          59d
cephfs-m-tf-notebook-deployment-7d77bcb77d-zxzt2      1/1     Running     0          59d
cephfs-m-tf-train-graph-deployment-55454b5f8c-gxdvr   1/1     Running     1          59d
cephfs-provisioner-b6b8f5f78-pbthg                    1/1     Running     5          27d
cephfsstatpod                                         0/1     Completed   0          17d
task-20190521115518-76246                             0/1     Error       0          27d
task-20190521115630-93065                             0/1     Error       0          27d
task-20190605154654-70546                             0/1     Error       0          12d
task-20190605154843-56929                             0/1     Error       0          12d
task-20190605154913-30617                             0/1     Pending     0          12d
temp-95996d9d8-rks7m                                  1/1     Running     1          43d
```
没有找到与PaddleJob相关的pod.

`fluid_job_dist_train.yaml`的内容如下：
```
apiVersion: paddlepaddle.org/v1
kind: PaddleJob
metadata:
  name: songhao-test-paddle-job
spec:
  image: "dev.harbor.oppoadd.com/mlplatform/paddle-dist-train-test:1.0"
  port: 7164
  ports_num: 1
  ports_num_for_sparse: 1
  fault_tolerant: false
  trainer:
    entrypoint: "python /workspace/dist_train.py"
    workspace: "/workspace"
    passes: 50
    min-instance: 3
    max-instance: 2
    resources:
      limits:
        cpu: "200m"
        memory: "200Mi"
      requests:
        cpu: "200m"
        memory: "200Mi"
  pserver:
    min-instance: 2
    max-instance: 2
    resources:
      limits:
        cpu: "800m"
        memory: "600Mi"
      requests:
        cpu: "500m"
        memory: "200Mi"
```
